import { JapanTimeline, TimelineActivity, JapanRegion, RegionWithDays } from '@/types/travel'; // Import JapanRegion và RegionWithDays

interface AdjustRequest {
  regions: RegionWithDays[]; // Đảm bảo kiểu dữ liệu chính xác
  totalDuration: number;
  travelStyles?: any[];
  interests?: any[];
  season?: any;
  overrideRequest?: string;
}

// Gọi Gemini và trả về JapanTimeline khớp frontend
export async function regenerateTimelineWithOverride(
  requestData: AdjustRequest
): Promise<JapanTimeline> {
  const response = await fetch('http://localhost:3000/api/ai/adjust-itinerary', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(requestData)
  });

  const result = await response.json();
  console.log("👉 Raw response from Next.js API:", result); // Log raw response

  if (!response.ok) { // Kiểm tra trạng thái HTTP response
    throw new Error(result.error || 'Failed to fetch itinerary from AI API');
  }

  if (!result.itinerary) {
    throw new Error('No itinerary returned in API response.');
  }

  let parsed;
  try {
    parsed = JSON.parse(result.itinerary); // Parse itinerary từ chuỗi JSON
    console.log("👉 Parsed itinerary on frontend:", JSON.stringify(parsed, null, 2)); // Log JSON đã parse
  } catch (err) {
    console.error("❌ Failed to parse AI itinerary JSON from API response:", err);
    throw new Error('Failed to parse AI itinerary JSON received from API. Please check Gemini output format.');
  }

  // 💡 Thêm kiểm tra cấu trúc cơ bản của output parsed
  if (!parsed || !Array.isArray(parsed.days)) {
    console.error("❌ Parsed data does not contain a 'days' array:", parsed);
    throw new Error("Invalid itinerary structure received from API. Missing 'days' array.");
  }


  const days = parsed.days.map((day: any, index: number) => {
    // 💡 Sửa: Tìm kiếm JapanRegion đầy đủ từ requestData.regions
    // Sử dụng toLowerCase() để so sánh không phân biệt chữ hoa/thường
    const foundRegionData = requestData.regions.find(
      (r: RegionWithDays) => r.region.name.toLowerCase() === (day.region?.toLowerCase() || '')
    );

    const timelineRegion: JapanRegion = foundRegionData?.region || {
      id: day.region ? day.region.toLowerCase().replace(/\s/g, '-') : `unknown-region-${index + 1}`, // Tạo ID giả định
      name: day.region || `Unknown Region Day ${index + 1}`,
      nameJapanese: '', // Có thể cần logic để lấy tên tiếng Nhật
      description: 'Region generated by AI',
      icon: '❓',
    };
    console.log(`👉 Mapped Timeline Region for Day ${day.dayNumber || index + 1}:`, timelineRegion);


    const normalizedActivities: TimelineActivity[] = (day.activities || []).map((a: any, i: number): TimelineActivity => ({
      id: a.id || `${day.dayNumber || index + 1}-activity-${i + 1}`, // Đảm bảo luôn có ID
      name: a.title || a.name || `Activity ${i + 1}`,
      description: a.description || '',
      startTime: normalizeTime(a.startTime || a.time || '09:00'), // Ưu tiên startTime, fallback time, rồi default
      duration: Number(a.duration) || 60,
      // 💡 Sửa: Xử lý cost mạnh mẽ hơn để tránh NaN
      estimatedCost: parseCost(a.cost),
      type: a.type || 'experience',
      icon: a.icon && typeof a.icon === 'string' && a.icon.length > 0 ? a.icon : '📍', // Đảm bảo icon là chuỗi và không rỗng
      location: a.location || 'Unknown'
    }));

    // 💡 Kiểm tra và log các hoạt động đã normalize
    console.log(`👉 Normalized Activities for Day ${day.dayNumber || index + 1}:`, normalizedActivities);

    return {
      dayNumber: day.dayNumber || index + 1,
      region: timelineRegion, // Sử dụng object JapanRegion đã được chuẩn hóa
      activities: normalizedActivities,
      totalCost: normalizedActivities.reduce(
        (sum, act) => sum + (act.estimatedCost ?? 0), 0
      )
    };
  });

  return {
    days,
    totalDuration: requestData.totalDuration,
    regions: requestData.regions, // Giữ nguyên regions ban đầu
    travelStyles: requestData.travelStyles || [],
    season: requestData.season || null
  };
}

// 🕐 Helper: chuẩn hóa time thành HH:MM
function normalizeTime(time: string | number): string {
  if (typeof time === 'number') {
      time = String(time); // Chuyển số thành chuỗi nếu Gemini trả về số
  }
  if (!time || typeof time !== 'string' || !time.includes(':')) {
    console.warn(`⚠️ Invalid time format received: "${time}". Defaulting to "09:00".`);
    return '09:00';
  }
  const [h, m] = time.split(':').map((v) => v.padStart(2, '0'));
  return `${h}:${m}`;
}

// 💰 Helper: Xử lý chi phí để tránh NaN
function parseCost(cost: any): number {
  if (typeof cost === 'number') {
    return cost; // Nếu đã là số thì trả về luôn
  }
  if (typeof cost === 'string') {
    // Loại bỏ tất cả ký tự không phải số hoặc dấu chấm
    const cleanedCost = cost.replace(/[^0-9.]/g, '');
    const parsed = parseFloat(cleanedCost);
    if (!isNaN(parsed)) {
      return parsed;
    }
  }
  console.warn(`⚠️ Invalid cost format received: "${cost}". Defaulting to 0.`);
  return 0; // Trả về 0 nếu không thể parse thành số
}